export const setupGuideLanguage = {
    sq: {
        sG: "Udhëzuesi i Konfigurimit të Wishlist Guru",
        sGSH: "Ju lutemi plotësoni hapat e mëposhtëm për të filluar përdorimin e aplikacionit",
        s1: "HAPI 1 nga 3: Zgjidhni Temën dhe Aktivizoni Aplikacionin",
        ct: "Zgjidh Temën",
        active: "Aktive",
        inActive: "Çaktivizuar",
        n2: "Këtu mund të zgjidhni ku dëshironi të aktivoni dhe testoni aplikacionin Wishlist Guru. Ju lutemi sigurohuni që të keni aktivizuar Wishlist Guru App Embed përmes Redaktorit të Temës.",
        n3: "Aktivizo",
        n4: "Një skedë e re do të hapet nga ku mund të aktivizoni bllokun e integrimit të temës që lidhet me aplikacionin tonë. Ndiqni pamjen e dhënë dhe më pas kthehuni këtu për të vazhduar me hapin tjetër.",
        n5: "Shënim:",
        n6: "HAPI 1 - Zgjidh Temën dhe Aktivizo Aplikacionin",
        n7: "Aplikacioni aktualisht po funksionon në",
        n8: "Ndrysho Temën",
        n9: "Hapi 1 është i plotë, ju lutemi vazhdoni me hapin tjetër",

        r1: "HAPI 2 - Aktivizo Ikonën e Koleksionit",
        r2: "Cilësimet e Listës së Dëshirave në Faqen e Koleksioneve",
        r3: "Duhet të aktivizoni fillimisht këtë widget që funksionaliteti i Listës së Dëshirave të përdoret nga faqet e Koleksioneve dhe faqet e tjera.",
        r4: "E keni aktivizuar tashmë ikonën e koleksionit, ju lutemi vazhdoni me hapin tjetër",
        r5: "Hapi 2 është i plotë, ju lutemi vazhdoni me hapin tjetër",
        r6: "Mëparshëm",
        r7: "Ruaj dhe Vazhdo",
        r8: "HAPI 2 - Zgjidhni gjuhën për aplikacionin tuaj",
        r9: "Ruaj dhe Përfundo",

        q1: "HAPI 3 - Zgjidhni Gjuhën për Aplikacionin Tuaj",
        q2: "Nëse hasni ndonjë problem me përputhshmërinë e temës ose keni nevojë për ndonjë personalizim për aplikacionin tonë Wishlist Guru, mos hezitoni të na kontaktoni në",

        y1: "Gjuha e Anës së Administratorit",
        y2: "Zgjidhni gjuhën për anën tuaj të administratorit",
        y3: "Gjuha e Dyqanit",
        y4: "Zgjidhni gjuhën për mesazhet tuaja me tekst",

    },
    bg: {
        sG: "Ръководство за настройка на Wishlist Guru",
        sGSH: "Моля, завършете стъпките по-долу, за да започнете да използвате приложението",
        s1: "СТЪПКА 1 от 3: Изберете тема и активирайте приложението",
        ct: "Изберете тема",
        active: "Активно",
        inActive: "Деактивирано",
        n2: "Тук можете да изберете къде искате да активирате и тествате приложението Wishlist Guru. Моля, уверете се, че опцията Enable Wishlist Guru App Embed е активирана чрез редактора на теми.",
        n3: "Активирай",
        n4: "Ще се отвори нов раздел, от който можете да активирате блока за вграждане на темата, свързан с нашето приложение. Следвайте предоставения екран и след това се върнете тук, за да продължите със следващата стъпка.",
        n5: "Забележка:",
        n6: "СТЪПКА 1 - Изберете тема и активирайте приложението",
        n7: "Приложението в момента работи върху",
        n8: "Смяна на тема",
        n9: "Стъпка 1 е завършена, моля, продължете със следващата стъпка",

        r1: "СТЪПКА 2 - Активирайте иконата на колекцията",
        r2: "Настройки на Wishlist за страница с колекции",
        r3: "Първо трябва да активирате този уиджет, за да може функционалността на Wishlist да се използва от страниците с колекции и други страници.",
        r4: "Вече сте активирали иконата на колекцията, моля, продължете със следващата стъпка",
        r5: "Стъпка 2 е завършена, моля, продължете със следващата стъпка",
        r6: "Предишна",
        r7: "Запази и напред",
        r8: "СТЪПКА 2 - Изберете език за вашето приложение",
        r9: "Запази и завърши",

        q1: "СТЪПКА 3 - Изберете език за вашето приложение",
        q2: "Ако срещнете някакви проблеми със съвместимостта на темата или имате нужда от персонализация за нашето приложение Wishlist Guru, не се колебайте да се свържете с нас на",

        y1: "Език на администраторската страна",
        y2: "Изберете език за вашата администраторска страна",
        y3: "Език на магазина",
        y4: "Изберете език за вашите текстови съобщения",

    },
    "pt-BR": {
        sG: "Guia de Configuração do Wishlist Guru",
        sGSH: "Por favor, complete as etapas abaixo para começar a usar o aplicativo",
        s1: "ETAPA 1 de 3: Escolha o Tema e Ative o Aplicativo",
        ct: "Escolher Tema",
        active: "Ativo",
        inActive: "Desativado",
        n2: "Aqui você pode escolher onde deseja ativar e testar o aplicativo Wishlist Guru. Certifique-se de habilitar o Wishlist Guru App Embed pelo Editor de Tema.",
        n3: "Ativar",
        n4: "Uma nova aba será aberta de onde você poderá habilitar o bloco de incorporação do tema relacionado ao nosso aplicativo. Siga a captura de tela fornecida e depois retorne aqui para prosseguir para a próxima etapa.",
        n5: "Nota:",
        n6: "ETAPA 1 - Escolha o Tema e Ative o Aplicativo",
        n7: "Aplicativo atualmente funcionando em",
        n8: "Trocar Tema",
        n9: "Etapa 1 concluída, por favor prossiga para a próxima etapa",

        r1: "ETAPA 2 - Ativar Ícone da Coleção",
        r2: "Configurações de Wishlist na Página de Coleção",
        r3: "Você precisará habilitar este widget primeiro para que a funcionalidade de Wishlist possa ser usada em páginas de Coleção e outras páginas.",
        r4: "Você já ativou o ícone da coleção, por favor prossiga para a próxima etapa",
        r5: "Etapa 2 concluída, por favor prossiga para a próxima etapa",
        r6: "Anterior",
        r7: "Salvar e Próximo",
        r8: "ETAPA 2 - Escolha o idioma para seu aplicativo",
        r9: "Salvar e Concluir",

        q1: "ETAPA 3 - Escolha o Idioma para Seu Aplicativo",
        q2: "Se você encontrar algum problema de compatibilidade de tema ou precisar de personalização para nosso aplicativo Wishlist Guru, fique à vontade para entrar em contato conosco em",

        y1: "Idioma do Lado do Administrador",
        y2: "Selecione o idioma para o seu lado do administrador",
        y3: "Idioma da Loja",
        y4: "Selecione o idioma para suas mensagens de texto",

    },
    "zh-CN": {
        sG: "愿望清单Guru设置指南",
        sGSH: "请完成以下步骤以开始使用该应用",
        s1: "步骤1 共3步：选择主题并激活应用",
        ct: "选择主题",
        active: "已激活",
        inActive: "已停用",
        n2: "在这里您可以选择要在哪些地方启用和测试愿望清单Guru应用。请确保已通过主题编辑器启用愿望清单Guru应用嵌入。",
        n3: "启用",
        n4: "将会打开一个新标签页，您可以在其中启用与我们应用相关的主题嵌入块。按照提供的截图操作，然后返回此处继续下一步。",
        n5: "注意：",
        n6: "步骤1 - 选择主题并激活应用",
        n7: "应用当前正在运行于",
        n8: "切换主题",
        n9: "步骤1已完成，请继续下一步",

        r1: "步骤2 - 启用合集图标",
        r2: "合集页面愿望清单设置",
        r3: "您需要先启用此小部件，才能在合集页面和其他页面使用愿望清单功能。",
        r4: "您已经启用了合集图标，请继续下一步",
        r5: "步骤2已完成，请继续下一步",
        r6: "上一步",
        r7: "保存并下一步",
        r8: "步骤2 - 为您的应用选择语言",
        r9: "保存并完成",

        q1: "步骤3 - 为您的应用选择语言",
        q2: "如果您遇到任何主题兼容性问题或需要对我们的愿望清单Guru应用进行定制，请随时通过以下方式联系我们",

        y1: "管理员端语言",
        y2: "为您的管理员端选择语言",
        y3: "店面语言",
        y4: "为您的短信选择语言",

    },
    "zh-TW": {
        sG: "願望清單Guru設定指南",
        sGSH: "請完成以下步驟以開始使用此應用程式",
        s1: "步驟1 共3步：選擇主題並啟用應用程式",
        ct: "選擇主題",
        active: "已啟用",
        inActive: "已停用",
        n2: "在這裡您可以選擇在哪裡啟用和測試願望清單Guru應用程式。請確保已透過主題編輯器啟用願望清單Guru應用嵌入。",
        n3: "啟用",
        n4: "將會開啟一個新分頁，您可以在其中啟用與我們應用相關的主題嵌入區塊。按照提供的截圖操作，然後返回此處繼續下一步。",
        n5: "注意：",
        n6: "步驟1 - 選擇主題並啟用應用程式",
        n7: "應用程式目前正在運行於",
        n8: "切換主題",
        n9: "步驟1已完成，請繼續下一步",

        r1: "步驟2 - 啟用合集圖示",
        r2: "合集頁面願望清單設定",
        r3: "您需要先啟用此小工具，才能在合集頁面和其他頁面使用願望清單功能。",
        r4: "您已經啟用了合集圖示，請繼續下一步",
        r5: "步驟2已完成，請繼續下一步",
        r6: "上一步",
        r7: "儲存並下一步",
        r8: "步驟2 - 為您的應用選擇語言",
        r9: "儲存並完成",

        q1: "步驟3 - 為您的應用選擇語言",
        q2: "如果您遇到任何主題相容性問題或需要對我們的願望清單Guru應用進行自訂，請隨時透過以下方式與我們聯繫",

        y1: "管理員端語言",
        y2: "為您的管理員端選擇語言",
        y3: "店面語言",
        y4: "為您的簡訊選擇語言",

    },
    cs: {
        sG: "Průvodce nastavením Wishlist Guru",
        sGSH: "Dokončete prosím níže uvedené kroky, abyste mohli začít používat aplikaci",
        s1: "KROK 1 ze 3: Vyberte téma a aktivujte aplikaci",
        ct: "Vyberte téma",
        active: "Aktivní",
        inActive: "Deaktivováno",
        n2: "Zde si můžete vybrat, kde chcete aplikaci Wishlist Guru aktivovat a testovat. Ujistěte se, že je v editoru témat povoleno vložení aplikace Wishlist Guru.",
        n3: "Povolit",
        n4: "Otevře se nová karta, kde můžete povolit blok vložení tématu související s naší aplikací. Postupujte podle poskytnutého snímku obrazovky, poté se vraťte sem a pokračujte dalším krokem.",
        n5: "Poznámka:",
        n6: "KROK 1 - Vyberte téma a aktivujte aplikaci",
        n7: "Aplikace aktuálně funguje na",
        n8: "Přepnout téma",
        n9: "Krok 1 je dokončen, pokračujte prosím dalším krokem",

        r1: "KROK 2 - Povolit ikonu kolekce",
        r2: "Nastavení seznamu přání na stránce kolekce",
        r3: "Nejprve musíte povolit tento widget, aby bylo možné využívat funkci seznamu přání na stránkách kolekcí a jiných stránkách.",
        r4: "Ikonu kolekce jste již povolili, pokračujte prosím dalším krokem",
        r5: "Krok 2 je dokončen, pokračujte prosím dalším krokem",
        r6: "Předchozí",
        r7: "Uložit a pokračovat",
        r8: "KROK 2 - Vyberte jazyk pro vaši aplikaci",
        r9: "Uložit a dokončit",

        q1: "KROK 3 - Vyberte jazyk pro vaši aplikaci",
        q2: "Pokud narazíte na jakékoli problémy s kompatibilitou tématu nebo potřebujete přizpůsobení pro naši aplikaci Wishlist Guru, neváhejte nás kontaktovat na",

        y1: "Jazyk administrátorské strany",
        y2: "Vyberte jazyk pro svou administrátorskou stranu",
        y3: "Jazyk obchodu",
        y4: "Vyberte jazyk pro své textové zprávy",

    },
    da: {
        sG: "Wishlist Guru Opsætningsguide",
        sGSH: "Fuldfør venligst nedenstående trin for at begynde at bruge appen",
        s1: "TRIN 1 af 3: Vælg tema og aktiver app",
        ct: "Vælg tema",
        active: "Aktiv",
        inActive: "Deaktiveret",
        n2: "Her kan du vælge, hvor du vil aktivere og teste Wishlist Guru App. Sørg for, at 'Enable Wishlist Guru App Embed' er aktiveret via temaeditoren.",
        n3: "Aktiver",
        n4: "En ny fane åbnes, hvorfra du kan aktivere temablokrelateret indlejring til vores app. Følg det medfølgende skærmbillede, og vend derefter tilbage hertil for at fortsætte til næste trin.",
        n5: "Bemærk:",
        n6: "TRIN 1 - Vælg tema og aktiver app",
        n7: "Appen kører i øjeblikket på",
        n8: "Skift tema",
        n9: "Trin 1 er fuldført, fortsæt venligst til næste trin",

        r1: "TRIN 2 - Aktiver kollektionsikon",
        r2: "Indstillinger for ønskeliste på kollektionsside",
        r3: "Du skal først aktivere denne widget, så ønskelistefunktionen kan bruges fra kollektionssider og andre sider.",
        r4: "Du har allerede aktiveret kollektionsikonet, fortsæt venligst til næste trin",
        r5: "Trin 2 er fuldført, fortsæt venligst til næste trin",
        r6: "Forrige",
        r7: "Gem og næste",
        r8: "TRIN 2 - Vælg sprog til din app",
        r9: "Gem og fuldfør",

        q1: "TRIN 3 - Vælg sprog til din app",
        q2: "Hvis du oplever problemer med temakompatibilitet eller har brug for tilpasning til vores Wishlist Guru-app, er du velkommen til at kontakte os på",

        y1: "Admin-side sprog",
        y2: "Vælg sproget til din admin-side",
        y3: "Butiksfront sprog",
        y4: "Vælg sproget til dine tekstbeskeder",

    },
    nl: {
        sG: "Wishlist Guru Installatiehandleiding",
        sGSH: "Voltooi alstublieft de onderstaande stappen om de app te gaan gebruiken",
        s1: "STAP 1 van 3: Kies thema en activeer app",
        ct: "Kies thema",
        active: "Actief",
        inActive: "Gedeactiveerd",
        n2: "Hier kunt u kiezen waar u de Wishlist Guru App wilt activeren en testen. Zorg ervoor dat de optie 'Enable Wishlist Guru App Embed' is ingeschakeld via de thema-editor.",
        n3: "Inschakelen",
        n4: "Er wordt een nieuw tabblad geopend waar u het thema-invoegblok met betrekking tot onze app kunt inschakelen. Volg de meegeleverde schermafbeelding en keer daarna terug om door te gaan naar de volgende stap.",
        n5: "Opmerking:",
        n6: "STAP 1 - Kies thema en activeer app",
        n7: "App werkt momenteel op",
        n8: "Thema wisselen",
        n9: "Stap 1 is voltooid, ga verder met de volgende stap",

        r1: "STAP 2 - Schakel collectie-icoon in",
        r2: "Wishlist-instellingen voor collectiepagina",
        r3: "U moet deze widget eerst inschakelen zodat de wishlist-functie gebruikt kan worden op collectiepagina's en andere pagina's.",
        r4: "U heeft het collectie-icoon al ingeschakeld, ga verder met de volgende stap",
        r5: "Stap 2 is voltooid, ga verder met de volgende stap",
        r6: "Vorige",
        r7: "Opslaan en volgende",
        r8: "STAP 2 - Kies taal voor uw app",
        r9: "Opslaan en voltooien",

        q1: "STAP 3 - Kies taal voor uw app",
        q2: "Als u problemen ondervindt met thema-compatibiliteit of aanpassingen nodig heeft voor onze Wishlist Guru-app, neem gerust contact met ons op via",

        y1: "Beheerderszijde Taal",
        y2: "Selecteer de taal voor uw beheerderszijde",
        y3: "Winkelzijde Taal",
        y4: "Selecteer de taal voor uw sms-berichten",
    },
    en: {
        sG: "Wishlist Guru Setup Guide",
        sGSH: "Please complete the steps below to start using the app",
        s1: "STEP 1 of 3: Choose Theme And Activate App",
        ct: "Choose Theme",
        active: "Active",
        inActive: "Deactivated",
        n2: "Here you can choose where you want to active and test the Wishlist Guru App. Please make sure to Enable Wishlist Guru App Embed is enabled via Theme Editor.",
        n3: "Enable",
        n4: "A new tab will open from where you can enable theme embed block related to our app. Follow the screenshot provided and then return back here and proceed to next step.",
        n5: "Note:",
        n6: "STEP 1 - Choose Theme And Activate App",
        n7: "App currently working on",
        n8: "Switch Theme",
        n9: "Step 1 is complete please proceed to next step",

        r1: "STEP 2 - Enable Collection Icon",
        r2: "Collection Page Wishlist Settings",
        r3: "You will need to Enable this widget first so Wishlist functionality can be used from Collection pages and other Pages.",
        r4: "You have already enabled collection icon, please proceed to next step",
        r5: "Step 2 is complete, please proceed to next step",
        r6: "Previous",
        r7: "Save And Next",
        r8: "STEP 2 - Choose language for your app",
        r9: "Save and Complete",

        q1: "STEP 3 - Choose Language For Your App",
        q2: "If you encounter any issues with theme compatibility or need any customization for our Wishlist Guru app, feel free to reach out to us at",

        y1: "Admin Side Language",
        y2: "Select the language for the your admin side",
        y3: "Store Front Language",
        y4: "Select language for your Text messages"
    },
    fi: {
        sG: "Wishlist Guru Asennusopas",
        sGSH: "Täytä alla olevat vaiheet aloittaaksesi sovelluksen käytön",
        s1: "VAIHE 1 / 3: Valitse teema ja aktivoi sovellus",
        ct: "Valitse teema",
        active: "Aktiivinen",
        inActive: "Pois käytöstä",
        n2: "Täällä voit valita, missä haluat aktivoida ja testata Wishlist Guru -sovelluksen. Varmista, että Wishlist Guru App Embed on otettu käyttöön teemaeditorissa.",
        n3: "Ota käyttöön",
        n4: "Uusi välilehti avautuu, josta voit ottaa käyttöön sovellukseemme liittyvän teemaosablokin. Seuraa annettua kuvakaappausta, palaa sitten takaisin tänne ja jatka seuraavaan vaiheeseen.",
        n5: "Huom:",
        n6: "VAIHE 1 - Valitse teema ja aktivoi sovellus",
        n7: "Sovellus toimii tällä hetkellä teemassa",
        n8: "Vaihda teemaa",
        n9: "Vaihe 1 on valmis, jatka seuraavaan vaiheeseen",

        r1: "VAIHE 2 - Ota kokoelmakuvake käyttöön",
        r2: "Kokoelmasivun toivelistasetukset",
        r3: "Sinun on ensin otettava tämä widget käyttöön, jotta toivelistatoiminto voidaan käyttää kokoelma- ja muilla sivuilla.",
        r4: "Olet jo ottanut kokoelmakuvakkeen käyttöön, jatka seuraavaan vaiheeseen",
        r5: "Vaihe 2 on valmis, jatka seuraavaan vaiheeseen",
        r6: "Edellinen",
        r7: "Tallenna ja jatka",
        r8: "VAIHE 2 - Valitse sovelluksesi kieli",
        r9: "Tallenna ja valmis",

        q1: "VAIHE 3 - Valitse sovelluksesi kieli",
        q2: "Jos kohtaat ongelmia teeman yhteensopivuuden kanssa tai tarvitset mukautuksia Wishlist Guru -sovelluksellemme, ota meihin rohkeasti yhteyttä osoitteessa",

        y1: "Ylläpitäjän puolen kieli",
        y2: "Valitse kieli ylläpitäjän puolelle",
        y3: "Kaupan kieli",
        y4: "Valitse kieli tekstiviesteillesi",

    },
    fil: {
        sG: "Gabay sa Pag-setup ng Wishlist Guru",
        sGSH: "Pakicomplete ang mga hakbang sa ibaba upang masimulan ang paggamit ng app",
        s1: "HAKBANG 1 sa 3: Piliin ang Tema at I-activate ang App",
        ct: "Piliin ang Tema",
        active: "Aktibo",
        inActive: "Hindi Aktibo",
        n2: "Dito mo mapipili kung saan mo gustong i-activate at subukan ang Wishlist Guru App. Siguraduhin na naka-enable ang 'Enable Wishlist Guru App Embed' sa pamamagitan ng theme editor.",
        n3: "I-enable",
        n4: "Magbubukas ng bagong tab kung saan maaari mong i-enable ang theme embed block na konektado sa aming app. Sundin ang screenshot na ibinigay, pagkatapos bumalik dito at magpatuloy sa susunod na hakbang.",
        n5: "Tandaan:",
        n6: "HAKBANG 1 - Piliin ang Tema at I-activate ang App",
        n7: "Kasalukuyang tumatakbo ang app sa",
        n8: "Palitan ang Tema",
        n9: "Nakumpleto na ang Hakbang 1, magpatuloy sa susunod na hakbang",

        r1: "HAKBANG 2 - I-enable ang Koleksyon Icon",
        r2: "Mga Setting ng Wishlist sa Koleksyon na Pahina",
        r3: "Kailangan mo munang i-enable ang widget na ito para magamit ang wishlist feature mula sa mga koleksyon at iba pang pahina.",
        r4: "Na-enable mo na ang koleksyon icon, magpatuloy sa susunod na hakbang",
        r5: "Nakumpleto na ang Hakbang 2, magpatuloy sa susunod na hakbang",
        r6: "Nakaraan",
        r7: "I-save at Susunod",
        r8: "HAKBANG 2 - Piliin ang Wika para sa Iyong App",
        r9: "I-save at Tapusin",

        q1: "HAKBANG 3 - Piliin ang Wika para sa Iyong App",
        q2: "Kung makakaranas ka ng anumang isyu sa theme compatibility o kailangan mo ng customization para sa aming Wishlist Guru app, huwag mag-atubiling makipag-ugnayan sa amin sa",

        y1: "Wika ng Admin Side",
        y2: "Piliin ang wika para sa iyong admin side",
        y3: "Wika ng Tindahan",
        y4: "Piliin ang wika para sa iyong mga text message",

    },
    fr: {
        sG: "Guide d’installation de Wishlist Guru",
        sGSH: "Veuillez compléter les étapes ci-dessous pour commencer à utiliser l’application",
        s1: "ÉTAPE 1 sur 3 : Choisissez un thème et activez l’application",
        ct: "Choisir un thème",
        active: "Actif",
        inActive: "Désactivé",
        n2: "Ici, vous pouvez choisir où activer et tester l’application Wishlist Guru. Assurez-vous que l’option « Activer l’intégration de Wishlist Guru » est activée via l’éditeur de thème.",
        n3: "Activer",
        n4: "Un nouvel onglet s’ouvrira, où vous pourrez activer le bloc d’intégration du thème lié à notre application. Suivez la capture d’écran fournie, puis revenez ici pour continuer l’étape suivante.",
        n5: "Remarque :",
        n6: "ÉTAPE 1 - Choisissez un thème et activez l’application",
        n7: "L’application fonctionne actuellement sur",
        n8: "Changer de thème",
        n9: "L’étape 1 est terminée, veuillez continuer à l’étape suivante",

        r1: "ÉTAPE 2 - Activer l’icône de collection",
        r2: "Paramètres de la liste de souhaits sur la page collection",
        r3: "Vous devez d’abord activer ce widget pour pouvoir utiliser la fonction liste de souhaits depuis les pages collections et autres pages.",
        r4: "Vous avez déjà activé l’icône de collection, veuillez continuer à l’étape suivante",
        r5: "L’étape 2 est terminée, veuillez continuer à l’étape suivante",
        r6: "Précédent",
        r7: "Enregistrer et suivant",
        r8: "ÉTAPE 2 - Choisissez la langue de votre application",
        r9: "Enregistrer et terminer",

        q1: "ÉTAPE 3 - Choisissez la langue de votre application",
        q2: "Si vous rencontrez des problèmes de compatibilité avec le thème ou si vous avez besoin de personnalisations pour notre application Wishlist Guru, n’hésitez pas à nous contacter à",

        y1: "Langue du côté administrateur",
        y2: "Sélectionnez la langue pour votre côté administrateur",
        y3: "Langue de la vitrine",
        y4: "Sélectionnez la langue pour vos messages texte",
    },
    de: {
        sG: "Wishlist Guru Einrichtungsanleitung",
        sGSH: "Bitte führen Sie die untenstehenden Schritte aus, um die App zu verwenden",
        s1: "SCHRITT 1 von 3: Wählen Sie ein Theme und aktivieren Sie die App",
        ct: "Theme auswählen",
        active: "Aktiv",
        inActive: "Deaktiviert",
        n2: "Hier können Sie auswählen, wo Sie die Wishlist Guru App aktivieren und testen möchten. Stellen Sie sicher, dass die Option 'Wishlist Guru App Embed aktivieren' im Theme-Editor aktiviert ist.",
        n3: "Aktivieren",
        n4: "Ein neuer Tab wird geöffnet, auf dem Sie den Themen-Einbettungsblock für unsere App aktivieren können. Folgen Sie dem bereitgestellten Screenshot und kehren Sie dann hierher zurück, um mit dem nächsten Schritt fortzufahren.",
        n5: "Hinweis:",
        n6: "SCHRITT 1 - Wählen Sie ein Theme und aktivieren Sie die App",
        n7: "Die App läuft derzeit auf",
        n8: "Theme wechseln",
        n9: "Schritt 1 abgeschlossen, bitte fahren Sie mit dem nächsten Schritt fort",

        r1: "SCHRITT 2 - Sammlungssymbol aktivieren",
        r2: "Wunschlisten-Einstellungen auf der Sammlungsseite",
        r3: "Sie müssen dieses Widget zuerst aktivieren, damit die Wunschlistenfunktion von Sammlungsseiten und anderen Seiten aus genutzt werden kann.",
        r4: "Sie haben das Sammlungssymbol bereits aktiviert, bitte fahren Sie mit dem nächsten Schritt fort",
        r5: "Schritt 2 abgeschlossen, bitte fahren Sie mit dem nächsten Schritt fort",
        r6: "Zurück",
        r7: "Speichern und weiter",
        r8: "SCHRITT 2 - Wählen Sie die Sprache für Ihre App",
        r9: "Speichern und abschließen",

        q1: "SCHRITT 3 - Wählen Sie die Sprache für Ihre App",
        q2: "Wenn Sie auf Probleme mit der Theme-Kompatibilität stoßen oder Anpassungen für unsere Wishlist Guru App benötigen, können Sie uns gerne kontaktieren unter",

        y1: "Sprache der Administratorseite",
        y2: "Wählen Sie die Sprache für Ihre Administratorseite",
        y3: "Sprache des Schaufensters",
        y4: "Wählen Sie die Sprache für Ihre Textnachrichten",

    },
    el: {
        sG: "Οδηγός Ρύθμισης Wishlist Guru",
        sGSH: "Παρακαλούμε ολοκληρώστε τα παρακάτω βήματα για να ξεκινήσετε να χρησιμοποιείτε την εφαρμογή",
        s1: "ΒΗΜΑ 1 από 3: Επιλέξτε θέμα και ενεργοποιήστε την εφαρμογή",
        ct: "Επιλογή θέματος",
        active: "Ενεργό",
        inActive: "Ανενεργό",
        n2: "Εδώ μπορείτε να επιλέξετε πού θέλετε να ενεργοποιήσετε και να δοκιμάσετε την εφαρμογή Wishlist Guru. Βεβαιωθείτε ότι η επιλογή «Ενεργοποίηση ενσωμάτωσης Wishlist Guru App» είναι ενεργοποιημένη μέσω του επεξεργαστή θεμάτων.",
        n3: "Ενεργοποίηση",
        n4: "Θα ανοίξει μια νέα καρτέλα, όπου μπορείτε να ενεργοποιήσετε το μπλοκ ενσωμάτωσης θέματος που σχετίζεται με την εφαρμογή μας. Ακολουθήστε το παρεχόμενο στιγμιότυπο οθόνης και στη συνέχεια επιστρέψτε εδώ για να συνεχίσετε στο επόμενο βήμα.",
        n5: "Σημείωση:",
        n6: "ΒΗΜΑ 1 - Επιλέξτε θέμα και ενεργοποιήστε την εφαρμογή",
        n7: "Η εφαρμογή εκτελείται αυτήν τη στιγμή στο",
        n8: "Αλλαγή θέματος",
        n9: "Το Βήμα 1 ολοκληρώθηκε, συνεχίστε στο επόμενο βήμα",

        r1: "ΒΗΜΑ 2 - Ενεργοποίηση εικονιδίου συλλογής",
        r2: "Ρυθμίσεις λίστας επιθυμιών στη σελίδα συλλογής",
        r3: "Πρέπει πρώτα να ενεργοποιήσετε αυτό το widget ώστε να είναι διαθέσιμη η λειτουργία λίστας επιθυμιών από σελίδες συλλογών και άλλες σελίδες.",
        r4: "Έχετε ήδη ενεργοποιήσει το εικονίδιο συλλογής, συνεχίστε στο επόμενο βήμα",
        r5: "Το Βήμα 2 ολοκληρώθηκε, συνεχίστε στο επόμενο βήμα",
        r6: "Προηγούμενο",
        r7: "Αποθήκευση και επόμενο",
        r8: "ΒΗΜΑ 2 - Επιλέξτε γλώσσα για την εφαρμογή σας",
        r9: "Αποθήκευση και ολοκλήρωση",

        q1: "ΒΗΜΑ 3 - Επιλέξτε γλώσσα για την εφαρμογή σας",
        q2: "Αν αντιμετωπίσετε προβλήματα συμβατότητας με το θέμα ή χρειάζεστε προσαρμογές για την εφαρμογή Wishlist Guru, μη διστάσετε να επικοινωνήσετε μαζί μας στο",

        y1: "Γλώσσα πλευράς διαχειριστή",
        y2: "Επιλέξτε τη γλώσσα για την πλευρά του διαχειριστή σας",
        y3: "Γλώσσα καταστήματος",
        y4: "Επιλέξτε τη γλώσσα για τα μηνύματά σας κειμένου",

    },
    hu: {
        sG: "Wishlist Guru Beállítási Útmutató",
        sGSH: "Kérjük, fejezze be az alábbi lépéseket az alkalmazás használatának megkezdéséhez",
        s1: "1. LÉPÉS a 3-ból: Téma kiválasztása és alkalmazás aktiválása",
        ct: "Téma kiválasztása",
        active: "Aktív",
        inActive: "Deaktiválva",
        n2: "Itt kiválaszthatja, hol szeretné aktiválni és tesztelni a Wishlist Guru alkalmazást. Kérjük, győződjön meg róla, hogy a Wishlist Guru App Embed engedélyezve van a Téma Szerkesztőben.",
        n3: "Engedélyezés",
        n4: "Egy új fül fog megnyílni, ahonnan engedélyezheti az alkalmazásunkhoz kapcsolódó téma beágyazási blokkot. Kövesse a mellékelt képernyőképet, majd térjen vissza ide és folytassa a következő lépéssel.",
        n5: "Megjegyzés:",
        n6: "1. LÉPÉS - Téma kiválasztása és alkalmazás aktiválása",
        n7: "Az alkalmazás jelenleg ezen működik:",
        n8: "Téma váltása",
        n9: "1. lépés kész, kérem folytassa a következő lépéssel",

        r1: "2. LÉPÉS - Gyűjtemény ikon engedélyezése",
        r2: "Gyűjtemény oldal kívánságlista beállításai",
        r3: "Először engedélyeznie kell ezt a widgetet, hogy a kívánságlista funkció elérhető legyen a gyűjtemény és más oldalakon.",
        r4: "Már engedélyezte a gyűjtemény ikont, kérem folytassa a következő lépéssel",
        r5: "2. lépés kész, kérem folytassa a következő lépéssel",
        r6: "Előző",
        r7: "Mentés és Tovább",
        r8: "2. LÉPÉS - Válasszon nyelvet az alkalmazásához",
        r9: "Mentés és Befejezés",

        q1: "3. LÉPÉS - Válasszon nyelvet az alkalmazásához",
        q2: "Ha bármilyen problémát tapasztal a téma kompatibilitásával kapcsolatban, vagy bármilyen testreszabásra van szüksége a Wishlist Guru alkalmazásunkhoz, forduljon hozzánk bizalommal a következő címen:",

        y1: "Admin oldal nyelve",
        y2: "Válassza ki az admin oldal nyelvét",
        y3: "Bolt előlap nyelve",
        y4: "Válassza ki a nyelvet a szöveges üzeneteihez",

    },
    ga: {
        sG: "Treoir Socraithe Wishlist Guru",
        sGSH: "Críochnaigh na céimeanna thíos le tosú ag úsáid an aip",
        s1: "CÉIM 1 as 3: Roghnaigh Téama Agus Gníomhachtaigh an Aip",
        ct: "Roghnaigh Téama",
        active: "Gníomhach",
        inActive: "Díghníomhachtaithe",
        n2: "Anseo is féidir leat roghnú cá háit is mian leat an aip Wishlist Guru a ghníomhachtú agus a thástáil. Bí cinnte go bhfuil Wishlist Guru App Embed cumasaithe tríd an Eagarthóir Téama.",
        n3: "Cumasaigh",
        n4: "Osclófar cluaisín nua as a dtiocfaidh tú in ann bloc leabaithe téama a bhaineann lenár n-aip a chumasú. Lean an seat scáileáin a chuirtear ar fáil agus ansin filleadh ar ais anseo agus lean ar aghaidh chuig an gcéad chéim eile.",
        n5: "Nóta:",
        n6: "CÉIM 1 - Roghnaigh Téama Agus Gníomhachtaigh an Aip",
        n7: "Aip ag obair faoi láthair ar",
        n8: "Athraigh Téama",
        n9: "Tá Céim 1 críochnaithe, lean ar aghaidh chuig an gcéad chéim eile",

        r1: "CÉIM 2 - Cumasaigh Deilbhín Bailiúcháin",
        r2: "Socruithe Leathanaigh Bhailiúcháin don Wishlist",
        r3: "Caithfidh tú an giuirléid seo a chumasú ar dtús ionas gur féidir an fheidhmiúlacht Wishlist a úsáid ó leathanaigh bhailiúcháin agus leathanaigh eile.",
        r4: "Tá an deilbhín bailiúcháin cumasaithe agat cheana féin, lean ar aghaidh chuig an gcéad chéim eile",
        r5: "Tá Céim 2 críochnaithe, lean ar aghaidh chuig an gcéad chéim eile",
        r6: "Roimhe Seo",
        r7: "Sábháil Agus Ar Aghaidh",
        r8: "CÉIM 2 - Roghnaigh teanga don aip",
        r9: "Sábháil agus Críochnaigh",

        q1: "CÉIM 3 - Roghnaigh Teanga don Aip",
        q2: "Má thagann aon fhadhbanna ort le comhoiriúnacht téama nó má theastaíonn saincheapadh ar bith duit dár n-aip Wishlist Guru, bíodh leisce ort teagmháil a dhéanamh linn ag",

        y1: "Teanga Thaobh an Riarthóra",
        y2: "Roghnaigh an teanga do thaobh an riarthóra",
        y3: "Teanga Tosaigh an Stór",
        y4: "Roghnaigh an teanga do do theachtaireachtaí téacs",

    },
    it: {
        sG: "Guida alla Configurazione di Wishlist Guru",
        sGSH: "Completa i passaggi seguenti per iniziare a usare l'app",
        s1: "FASE 1 di 3: Scegli il Tema e Attiva l'App",
        ct: "Scegli Tema",
        active: "Attivo",
        inActive: "Disattivato",
        n2: "Qui puoi scegliere dove attivare e testare l'app Wishlist Guru. Assicurati che l'Embed di Wishlist Guru sia abilitato tramite l'Editor del Tema.",
        n3: "Abilita",
        n4: "Si aprirà una nuova scheda da cui potrai abilitare il blocco di incorporamento tema relativo alla nostra app. Segui lo screenshot fornito e poi torna qui per procedere al passaggio successivo.",
        n5: "Nota:",
        n6: "FASE 1 - Scegli il Tema e Attiva l'App",
        n7: "App attualmente in uso su",
        n8: "Cambia Tema",
        n9: "La fase 1 è completata, procedi al passaggio successivo",

        r1: "FASE 2 - Abilita Icona Collezione",
        r2: "Impostazioni Wishlist della Pagina Collezione",
        r3: "Devi prima abilitare questo widget affinché la funzionalità Wishlist possa essere utilizzata dalle pagine Collezione e altre pagine.",
        r4: "Hai già abilitato l'icona collezione, procedi al passaggio successivo",
        r5: "La fase 2 è completata, procedi al passaggio successivo",
        r6: "Precedente",
        r7: "Salva e Avanti",
        r8: "FASE 2 - Scegli la lingua per la tua app",
        r9: "Salva e Completa",

        q1: "FASE 3 - Scegli la Lingua per la tua App",
        q2: "Se riscontri problemi di compatibilità del tema o hai bisogno di personalizzazioni per la nostra app Wishlist Guru, non esitare a contattarci a",

        y1: "Lingua lato amministratore",
        y2: "Seleziona la lingua per il lato amministratore",
        y3: "Lingua del negozio",
        y4: "Seleziona la lingua per i tuoi messaggi di testo",

    },
    id: {
        sG: "Panduan Pengaturan Wishlist Guru",
        sGSH: "Silakan selesaikan langkah-langkah di bawah ini untuk mulai menggunakan aplikasi",
        s1: "LANGKAH 1 dari 3: Pilih Tema dan Aktifkan Aplikasi",
        ct: "Pilih Tema",
        active: "Aktif",
        inActive: "Nonaktif",
        n2: "Di sini Anda dapat memilih di mana ingin mengaktifkan dan menguji Aplikasi Wishlist Guru. Pastikan Embed Aplikasi Wishlist Guru diaktifkan melalui Editor Tema.",
        n3: "Aktifkan",
        n4: "Tab baru akan terbuka di mana Anda dapat mengaktifkan blok embed tema yang terkait dengan aplikasi kami. Ikuti tangkapan layar yang diberikan lalu kembali ke sini dan lanjutkan ke langkah berikutnya.",
        n5: "Catatan:",
        n6: "LANGKAH 1 - Pilih Tema dan Aktifkan Aplikasi",
        n7: "Aplikasi saat ini berjalan di",
        n8: "Ganti Tema",
        n9: "Langkah 1 selesai, silakan lanjutkan ke langkah berikutnya",

        r1: "LANGKAH 2 - Aktifkan Ikon Koleksi",
        r2: "Pengaturan Wishlist Halaman Koleksi",
        r3: "Anda harus mengaktifkan widget ini terlebih dahulu agar fungsionalitas Wishlist dapat digunakan dari halaman Koleksi dan halaman lainnya.",
        r4: "Anda sudah mengaktifkan ikon koleksi, silakan lanjutkan ke langkah berikutnya",
        r5: "Langkah 2 selesai, silakan lanjutkan ke langkah berikutnya",
        r6: "Sebelumnya",
        r7: "Simpan dan Lanjut",
        r8: "LANGKAH 2 - Pilih bahasa untuk aplikasi Anda",
        r9: "Simpan dan Selesai",

        q1: "LANGKAH 3 - Pilih Bahasa untuk Aplikasi Anda",
        q2: "Jika Anda mengalami masalah dengan kompatibilitas tema atau memerlukan kustomisasi untuk aplikasi Wishlist Guru kami, jangan ragu untuk menghubungi kami di",

        y1: "Bahasa Sisi Admin",
        y2: "Pilih bahasa untuk sisi admin Anda",
        y3: "Bahasa Toko",
        y4: "Pilih bahasa untuk pesan teks Anda",

    },
    ja: {
        sG: "ウィッシュリストGuruセットアップガイド",
        sGSH: "アプリを使用開始するには以下の手順を完了してください",
        s1: "ステップ1/3: テーマを選択してアプリを有効化",
        ct: "テーマを選択",
        active: "有効",
        inActive: "無効",
        n2: "ここで、Wishlist Guruアプリを有効化してテストしたい場所を選択できます。テーマエディタからWishlist Guruアプリの埋め込みを有効にしてください。",
        n3: "有効化",
        n4: "新しいタブが開き、アプリ関連のテーマ埋め込みブロックを有効にできます。スクリーンショットに従い、その後ここに戻って次のステップに進んでください。",
        n5: "注意:",
        n6: "ステップ1 - テーマを選択してアプリを有効化",
        n7: "現在アプリが動作しているテーマ:",
        n8: "テーマを切り替える",
        n9: "ステップ1が完了しました。次のステップに進んでください。",

        r1: "ステップ2 - コレクションアイコンを有効化",
        r2: "コレクションページ ウィッシュリスト設定",
        r3: "まずこのウィジェットを有効化する必要があります。そうすることで、コレクションページやその他のページからウィッシュリスト機能を利用できます。",
        r4: "コレクションアイコンはすでに有効化されています。次のステップに進んでください。",
        r5: "ステップ2が完了しました。次のステップに進んでください。",
        r6: "前へ",
        r7: "保存して次へ",
        r8: "ステップ2 - アプリの言語を選択",
        r9: "保存して完了",

        q1: "ステップ3 - アプリの言語を選択",
        q2: "テーマ互換性の問題やWishlist Guruアプリのカスタマイズが必要な場合は、遠慮なくこちらまでご連絡ください:",

        y1: "管理者側の言語",
        y2: "管理者側の言語を選択してください",
        y3: "ストアフロントの言語",
        y4: "テキストメッセージの言語を選択してください",

    },
    ko: {
        sG: "위시리스트 Guru 설정 가이드",
        sGSH: "앱을 사용하려면 아래 단계를 완료하세요",
        s1: "3단계 중 1단계: 테마 선택 및 앱 활성화",
        ct: "테마 선택",
        active: "활성화됨",
        inActive: "비활성화됨",
        n2: "여기에서 Wishlist Guru 앱을 활성화하고 테스트할 위치를 선택할 수 있습니다. 테마 편집기에서 Wishlist Guru 앱 임베드가 활성화되어 있는지 확인하세요.",
        n3: "활성화",
        n4: "새 탭이 열리며 앱 관련 테마 임베드 블록을 활성화할 수 있습니다. 제공된 스크린샷을 따르고, 여기로 돌아와 다음 단계로 진행하세요.",
        n5: "참고:",
        n6: "1단계 - 테마 선택 및 앱 활성화",
        n7: "현재 앱이 작동 중인 테마:",
        n8: "테마 전환",
        n9: "1단계가 완료되었습니다. 다음 단계로 진행하세요.",

        r1: "2단계 - 컬렉션 아이콘 활성화",
        r2: "컬렉션 페이지 위시리스트 설정",
        r3: "먼저 이 위젯을 활성화해야 컬렉션 페이지 및 다른 페이지에서 위시리스트 기능을 사용할 수 있습니다.",
        r4: "컬렉션 아이콘이 이미 활성화되어 있습니다. 다음 단계로 진행하세요.",
        r5: "2단계가 완료되었습니다. 다음 단계로 진행하세요.",
        r6: "이전",
        r7: "저장 후 다음",
        r8: "2단계 - 앱 언어 선택",
        r9: "저장 후 완료",

        q1: "3단계 - 앱 언어 선택",
        q2: "테마 호환성 문제나 Wishlist Guru 앱의 맞춤 설정이 필요하다면 언제든지 다음으로 문의해 주세요:",

        y1: "관리자 측 언어",
        y2: "관리자 측의 언어를 선택하세요",
        y3: "스토어프론트 언어",
        y4: "문자 메시지의 언어를 선택하세요",

    },
    lt: {
        sG: "Pageidavimų sąrašo Guru nustatymo gidas",
        sGSH: "Norėdami pradėti naudoti programėlę, užbaikite šiuos veiksmus",
        s1: "1 ŽINGSNIS iš 3: Pasirinkite temą ir aktyvuokite programėlę",
        ct: "Pasirinkite temą",
        active: "Aktyvuota",
        inActive: "Deaktyvuota",
        n2: "Čia galite pasirinkti, kur norite aktyvuoti ir išbandyti Wishlist Guru programėlę. Įsitikinkite, kad programėlės įterpimas per temos redaktorių yra įjungtas.",
        n3: "Įjungti",
        n4: "Atsidarys naujas skirtukas, kuriame galėsite įjungti su mūsų programėle susijusį temos įterpimo bloką. Vadovaukitės pateikta ekrano nuotrauka, tada grįžkite čia ir tęskite kitą žingsnį.",
        n5: "Pastaba:",
        n6: "1 ŽINGSNIS - Pasirinkite temą ir aktyvuokite programėlę",
        n7: "Programėlė šiuo metu veikia su tema:",
        n8: "Pakeisti temą",
        n9: "1 žingsnis baigtas, pereikite prie kito žingsnio.",

        r1: "2 ŽINGSNIS - Įjunkite kolekcijos piktogramą",
        r2: "Kolekcijos puslapio pageidavimų sąrašo nustatymai",
        r3: "Pirmiausia turite įjungti šį valdiklį, kad pageidavimų sąrašo funkcionalumas veiktų iš kolekcijos ir kitų puslapių.",
        r4: "Kolekcijos piktograma jau įjungta, pereikite prie kito žingsnio.",
        r5: "2 žingsnis baigtas, pereikite prie kito žingsnio.",
        r6: "Atgal",
        r7: "Išsaugoti ir kitas",
        r8: "2 ŽINGSNIS - Pasirinkite programėlės kalbą",
        r9: "Išsaugoti ir baigti",

        q1: "3 ŽINGSNIS - Pasirinkite programėlės kalbą",
        q2: "Jei susiduriate su temos suderinamumo problemomis arba reikia mūsų Wishlist Guru programėlės pritaikymo, nedvejodami susisiekite su mumis:",

        y1: "Administratoriaus pusės kalba",
        y2: "Pasirinkite kalbą savo administratoriaus pusei",
        y3: "Parduotuvės kalba",
        y4: "Pasirinkite kalbą savo tekstiniams pranešimams",

    },
    nb: {
        sG: "Wishlist Guru oppsettguide",
        sGSH: "Fullfør trinnene nedenfor for å begynne å bruke appen",
        s1: "TRINN 1 av 3: Velg tema og aktiver appen",
        ct: "Velg tema",
        active: "Aktiv",
        inActive: "Deaktivert",
        n2: "Her kan du velge hvor du vil aktivere og teste Wishlist Guru-appen. Sørg for at app-embed er aktivert via temaeditoren.",
        n3: "Aktiver",
        n4: "En ny fane åpnes der du kan aktivere tema-embed-blokken knyttet til appen vår. Følg skjermbildet som er gitt, og kom deretter tilbake hit for å gå videre til neste trinn.",
        n5: "Merk:",
        n6: "TRINN 1 - Velg tema og aktiver appen",
        n7: "Appen kjører for øyeblikket på",
        n8: "Bytt tema",
        n9: "Trinn 1 er fullført, vennligst gå videre til neste trinn.",

        r1: "TRINN 2 - Aktiver kolleksjonsikon",
        r2: "Innstillinger for ønskeliste på kolleksjonsside",
        r3: "Du må aktivere denne widgeten først slik at ønskelistefunksjonen kan brukes fra kolleksjonssider og andre sider.",
        r4: "Du har allerede aktivert kolleksjonsikonet, vennligst gå videre til neste trinn.",
        r5: "Trinn 2 er fullført, vennligst gå videre til neste trinn.",
        r6: "Forrige",
        r7: "Lagre og neste",
        r8: "TRINN 2 - Velg språk for appen din",
        r9: "Lagre og fullfør",

        q1: "TRINN 3 - Velg språk for appen din",
        q2: "Hvis du opplever problemer med temakompatibilitet eller trenger tilpasning for vår Wishlist Guru-app, ta gjerne kontakt med oss på:",

        y1: "Admin-side språk",
        y2: "Velg språket for admin-siden din",
        y3: "Butikkfront språk",
        y4: "Velg språket for tekstmeldingene dine",
    },
    pl: {
        sG: "Przewodnik konfiguracji Wishlist Guru",
        sGSH: "Proszę wykonaj poniższe kroki, aby rozpocząć korzystanie z aplikacji",
        s1: "KROK 1 z 3: Wybierz motyw i aktywuj aplikację",
        ct: "Wybierz motyw",
        active: "Aktywne",
        inActive: "Dezaktywowane",
        n2: "Tutaj możesz wybrać, gdzie chcesz aktywować i przetestować aplikację Wishlist Guru. Upewnij się, że opcja Włącz Wishlist Guru App Embed jest włączona w Edytorze motywów.",
        n3: "Włącz",
        n4: "Otworzy się nowa karta, z której możesz włączyć blok osadzania motywu związany z naszą aplikacją. Postępuj zgodnie ze zrzutem ekranu i wróć tutaj, aby przejść do następnego kroku.",
        n5: "Uwaga:",
        n6: "KROK 1 - Wybierz motyw i aktywuj aplikację",
        n7: "Aplikacja obecnie działa na",
        n8: "Zmień motyw",
        n9: "Krok 1 zakończony, przejdź do następnego kroku",

        r1: "KROK 2 - Włącz ikonę kolekcji",
        r2: "Ustawienia listy życzeń strony kolekcji",
        r3: "Musisz najpierw włączyć ten widżet, aby funkcja listy życzeń mogła być używana na stronach kolekcji i innych stronach.",
        r4: "Ikona kolekcji została już włączona, przejdź do następnego kroku",
        r5: "Krok 2 zakończony, przejdź do następnego kroku",
        r6: "Poprzedni",
        r7: "Zapisz i dalej",
        r8: "KROK 2 - Wybierz język dla swojej aplikacji",
        r9: "Zapisz i zakończ",

        q1: "KROK 3 - Wybierz język dla swojej aplikacji",
        q2: "Jeśli napotkasz jakiekolwiek problemy ze zgodnością motywu lub potrzebujesz dostosowania naszej aplikacji Wishlist Guru, skontaktuj się z nami pod adresem",

        y1: "Język panelu administratora",
        y2: "Wybierz język dla panelu administratora",
        y3: "Język sklepu",
        y4: "Wybierz język dla swoich wiadomości tekstowych",
    },
    "pt-PT": {
        sG: "Guia de Configuração do Wishlist Guru",
        sGSH: "Por favor, complete os passos abaixo para começar a usar a aplicação",
        s1: "PASSO 1 de 3: Escolha o tema e ative a aplicação",
        ct: "Escolher tema",
        active: "Ativo",
        inActive: "Desativado",
        n2: "Aqui pode escolher onde deseja ativar e testar a aplicação Wishlist Guru. Certifique-se de que a opção Ativar Wishlist Guru App Embed está ativada através do Editor de Temas.",
        n3: "Ativar",
        n4: "Uma nova aba será aberta onde pode ativar o bloco de incorporação do tema relacionado com a nossa aplicação. Siga a captura de ecrã fornecida e volte aqui para continuar para o próximo passo.",
        n5: "Nota:",
        n6: "PASSO 1 - Escolha o tema e ative a aplicação",
        n7: "Aplicação atualmente a funcionar em",
        n8: "Mudar tema",
        n9: "O Passo 1 está concluído, por favor prossiga para o próximo passo",

        r1: "PASSO 2 - Ativar ícone da coleção",
        r2: "Definições da lista de desejos da página de coleção",
        r3: "Deverá ativar primeiro este widget para que a funcionalidade da lista de desejos possa ser utilizada nas páginas de coleção e noutras páginas.",
        r4: "Já ativou o ícone da coleção, por favor prossiga para o próximo passo",
        r5: "Passo 2 concluído, por favor prossiga para o próximo passo",
        r6: "Anterior",
        r7: "Guardar e próximo",
        r8: "PASSO 2 - Escolha o idioma da sua aplicação",
        r9: "Guardar e concluir",

        q1: "PASSO 3 - Escolha o idioma da sua aplicação",
        q2: "Se encontrar quaisquer problemas de compatibilidade com o tema ou necessitar de personalização da nossa aplicação Wishlist Guru, entre em contacto connosco em",

        y1: "Idioma do lado do administrador",
        y2: "Selecione o idioma para o seu lado do administrador",
        y3: "Idioma da loja",
        y4: "Selecione o idioma para as suas mensagens de texto",

    },
    ro: {
        sG: "Ghid de configurare Wishlist Guru",
        sGSH: "Vă rugăm să finalizați pașii de mai jos pentru a începe să utilizați aplicația",
        s1: "PASUL 1 din 3: Alege tema și activează aplicația",
        ct: "Alege tema",
        active: "Activ",
        inActive: "Dezactivat",
        n2: "Aici puteți alege unde doriți să activați și să testați aplicația Wishlist Guru. Vă rugăm să vă asigurați că opțiunea Activați Wishlist Guru App Embed este activată prin Editorul de teme.",
        n3: "Activează",
        n4: "Se va deschide o filă nouă de unde puteți activa blocul de încorporare a temei legat de aplicația noastră. Urmați captura de ecran furnizată, apoi reveniți aici și continuați cu pasul următor.",
        n5: "Notă:",
        n6: "PASUL 1 - Alege tema și activează aplicația",
        n7: "Aplicația rulează în prezent pe",
        n8: "Schimbă tema",
        n9: "Pasul 1 este complet, vă rugăm să continuați cu pasul următor",

        r1: "PASUL 2 - Activează pictograma colecției",
        r2: "Setări pentru lista de dorințe din pagina de colecție",
        r3: "Trebuie să activați mai întâi acest widget pentru ca funcționalitatea listei de dorințe să poată fi utilizată din paginile de colecții și alte pagini.",
        r4: "Ați activat deja pictograma colecției, vă rugăm să continuați cu pasul următor",
        r5: "Pasul 2 este complet, vă rugăm să continuați cu pasul următor",
        r6: "Înapoi",
        r7: "Salvează și următorul",
        r8: "PASUL 2 - Alege limba aplicației tale",
        r9: "Salvează și finalizează",

        q1: "PASUL 3 - Alege limba aplicației tale",
        q2: "Dacă întâmpinați probleme de compatibilitate cu tema sau aveți nevoie de personalizare pentru aplicația Wishlist Guru, nu ezitați să ne contactați la",

        y1: "Limba părții de administrator",
        y2: "Selectați limba pentru partea de administrator",
        y3: "Limba magazinului",
        y4: "Selectați limba pentru mesajele dvs. text",

    },
    ru: {
        sG: "Руководство по настройке Wishlist Guru",
        sGSH: "Пожалуйста, выполните шаги ниже, чтобы начать использовать приложение",
        s1: "ШАГ 1 из 3: Выберите тему и активируйте приложение",
        ct: "Выбрать тему",
        active: "Активно",
        inActive: "Деактивировано",
        n2: "Здесь вы можете выбрать, где хотите активировать и протестировать приложение Wishlist Guru. Убедитесь, что в Редакторе тем включена опция Включить Wishlist Guru App Embed.",
        n3: "Включить",
        n4: "Откроется новая вкладка, где вы сможете включить блок встраивания темы, связанный с нашим приложением. Следуйте предоставленному скриншоту, затем вернитесь сюда и переходите к следующему шагу.",
        n5: "Примечание:",
        n6: "ШАГ 1 - Выберите тему и активируйте приложение",
        n7: "Приложение сейчас работает на",
        n8: "Сменить тему",
        n9: "Шаг 1 завершен, пожалуйста, переходите к следующему шагу",

        r1: "ШАГ 2 - Включите иконку коллекции",
        r2: "Настройки списка желаний на странице коллекции",
        r3: "Сначала необходимо включить этот виджет, чтобы функция списка желаний могла использоваться на страницах коллекций и других страницах.",
        r4: "Вы уже включили иконку коллекции, пожалуйста, переходите к следующему шагу",
        r5: "Шаг 2 завершен, пожалуйста, переходите к следующему шагу",
        r6: "Назад",
        r7: "Сохранить и далее",
        r8: "ШАГ 2 - Выберите язык для вашего приложения",
        r9: "Сохранить и завершить",

        q1: "ШАГ 3 - Выберите язык для вашего приложения",
        q2: "Если у вас возникнут проблемы с совместимостью темы или потребуется кастомизация нашего приложения Wishlist Guru, пожалуйста, свяжитесь с нами по адресу",

        y1: "Язык панели администратора",
        y2: "Выберите язык для вашей панели администратора",
        y3: "Язык витрины магазина",
        y4: "Выберите язык для ваших текстовых сообщений",

    },
    es: {
        sG: "Guía de configuración de Wishlist Guru",
        sGSH: "Por favor completa los pasos a continuación para comenzar a usar la aplicación",
        s1: "PASO 1 de 3: Elegir tema y activar la aplicación",
        ct: "Elegir tema",
        active: "Activo",
        inActive: "Desactivado",
        n2: "Aquí puedes elegir dónde deseas activar y probar la aplicación Wishlist Guru. Asegúrate de que la opción 'Enable Wishlist Guru App Embed' esté habilitada en el Editor de temas.",
        n3: "Habilitar",
        n4: "Se abrirá una nueva pestaña desde donde podrás habilitar el bloque de inserción de tema relacionado con nuestra aplicación. Sigue la captura de pantalla proporcionada, regresa aquí y continúa con el siguiente paso.",
        n5: "Nota:",
        n6: "PASO 1 - Elegir tema y activar la aplicación",
        n7: "Aplicación actualmente funcionando en",
        n8: "Cambiar tema",
        n9: "El paso 1 está completo, por favor continúa al siguiente paso",

        r1: "PASO 2 - Habilitar icono de colección",
        r2: "Configuración de lista de deseos en la página de colección",
        r3: "Primero deberás habilitar este widget para que la funcionalidad de la lista de deseos se pueda usar desde las páginas de colección y otras páginas.",
        r4: "Ya has habilitado el icono de colección, por favor continúa al siguiente paso",
        r5: "El paso 2 está completo, por favor continúa al siguiente paso",
        r6: "Anterior",
        r7: "Guardar y siguiente",
        r8: "PASO 2 - Elegir idioma para tu aplicación",
        r9: "Guardar y completar",

        q1: "PASO 3 - Elegir idioma para tu aplicación",
        q2: "Si encuentras algún problema con la compatibilidad del tema o necesitas personalización para nuestra aplicación Wishlist Guru, no dudes en contactarnos en",

        y1: "Idioma del lado del administrador",
        y2: "Seleccione el idioma para su lado del administrador",
        y3: "Idioma de la tienda",
        y4: "Seleccione el idioma para sus mensajes de texto",

    },
    sv: {
        sG: "Wishlist Guru installationsguide",
        sGSH: "Vänligen slutför stegen nedan för att börja använda appen",
        s1: "STEG 1 av 3: Välj tema och aktivera appen",
        ct: "Välj tema",
        active: "Aktiv",
        inActive: "Avaktiverad",
        n2: "Här kan du välja var du vill aktivera och testa Wishlist Guru-appen. Se till att 'Enable Wishlist Guru App Embed' är aktiverat via Temaredigeraren.",
        n3: "Aktivera",
        n4: "En ny flik öppnas där du kan aktivera temainbäddningsblocket relaterat till vår app. Följ den tillhandahållna skärmdumpen, återvänd hit och fortsätt till nästa steg.",
        n5: "Obs:",
        n6: "STEG 1 - Välj tema och aktivera appen",
        n7: "Appen fungerar för närvarande på",
        n8: "Byt tema",
        n9: "Steg 1 är slutfört, vänligen fortsätt till nästa steg",

        r1: "STEG 2 - Aktivera samlingsikon",
        r2: "Inställningar för önskelista på samlingssidan",
        r3: "Du måste först aktivera denna widget så att önskelistefunktionen kan användas från samlingssidor och andra sidor.",
        r4: "Du har redan aktiverat samlingsikonen, vänligen fortsätt till nästa steg",
        r5: "Steg 2 är slutfört, vänligen fortsätt till nästa steg",
        r6: "Föregående",
        r7: "Spara och nästa",
        r8: "STEG 2 - Välj språk för din app",
        r9: "Spara och slutför",

        q1: "STEG 3 - Välj språk för din app",
        q2: "Om du stöter på problem med temakompatibilitet eller behöver anpassningar för vår Wishlist Guru-app, tveka inte att kontakta oss på",

        y1: "Adminsida språk",
        y2: "Välj språket för din adminsida",
        y3: "Butiksfront språk",
        y4: "Välj språket för dina textmeddelanden",

    },
    tr: {
        sG: "Wishlist Guru Kurulum Rehberi",
        sGSH: "Uygulamayı kullanmaya başlamak için lütfen aşağıdaki adımları tamamlayın",
        s1: "ADIM 1 / 3: Tema Seç ve Uygulamayı Aktifleştir",
        ct: "Tema Seç",
        active: "Aktif",
        inActive: "Devre dışı",
        n2: "Buradan Wishlist Guru uygulamasını nerede aktifleştirmek ve test etmek istediğinizi seçebilirsiniz. Lütfen Tema Düzenleyicisi üzerinden 'Enable Wishlist Guru App Embed' seçeneğinin etkinleştirildiğinden emin olun.",
        n3: "Etkinleştir",
        n4: "Uygulamamızla ilgili tema gömme bloğunu etkinleştirebileceğiniz yeni bir sekme açılacaktır. Sağlanan ekran görüntüsünü takip edin, buraya geri dönün ve sonraki adıma geçin.",
        n5: "Not:",
        n6: "ADIM 1 - Tema Seç ve Uygulamayı Aktifleştir",
        n7: "Uygulama şu anda çalışıyor:",
        n8: "Temayı Değiştir",
        n9: "Adım 1 tamamlandı, lütfen sonraki adıma geçin",

        r1: "ADIM 2 - Koleksiyon İkonunu Etkinleştir",
        r2: "Koleksiyon Sayfası Dilek Listesi Ayarları",
        r3: "Bu widget'ı önce etkinleştirmeniz gerekir, böylece dilek listesi işlevselliği koleksiyon sayfalarından ve diğer sayfalardan kullanılabilir.",
        r4: "Koleksiyon ikonunu zaten etkinleştirdiniz, lütfen sonraki adıma geçin",
        r5: "Adım 2 tamamlandı, lütfen sonraki adıma geçin",
        r6: "Önceki",
        r7: "Kaydet ve İleri",
        r8: "ADIM 2 - Uygulamanız için dil seçin",
        r9: "Kaydet ve Tamamla",

        q1: "ADIM 3 - Uygulamanız için dil seçin",
        q2: "Tema uyumluluğu ile ilgili herhangi bir sorunla karşılaşırsanız veya Wishlist Guru uygulamamız için özelleştirme gerekiyorsa, bizimle iletişime geçmekten çekinmeyin:",

        y1: "Yönetici tarafı dili",
        y2: "Yönetici tarafınız için dili seçin",
        y3: "Mağaza dili",
        y4: "Metin mesajlarınız için dili seçin",

    },
    th: {
        sG: "คู่มือการติดตั้ง Wishlist Guru",
        sGSH: "โปรดทำตามขั้นตอนด้านล่างเพื่อเริ่มใช้งานแอป",
        s1: "ขั้นตอนที่ 1 จาก 3: เลือกธีมและเปิดใช้งานแอป",
        ct: "เลือกธีม",
        active: "เปิดใช้งาน",
        inActive: "ปิดใช้งาน",
        n2: "ที่นี่คุณสามารถเลือกได้ว่าจะเปิดใช้งานและทดสอบแอป Wishlist Guru ที่ไหน โปรดตรวจสอบให้แน่ใจว่าได้เปิดใช้งาน 'Enable Wishlist Guru App Embed' ผ่าน Theme Editor แล้ว",
        n3: "เปิดใช้งาน",
        n4: "แท็บใหม่จะถูกเปิดขึ้นเพื่อให้คุณเปิดใช้งานบล็อกฝังธีมที่เกี่ยวข้องกับแอปของเรา ทำตามภาพหน้าจอที่ให้มา จากนั้นกลับมาที่นี่และไปยังขั้นตอนถัดไป",
        n5: "หมายเหตุ:",
        n6: "ขั้นตอนที่ 1 - เลือกธีมและเปิดใช้งานแอป",
        n7: "แอปกำลังทำงานอยู่บน",
        n8: "สลับธีม",
        n9: "ขั้นตอนที่ 1 เสร็จสมบูรณ์แล้ว โปรดไปยังขั้นตอนถัดไป",

        r1: "ขั้นตอนที่ 2 - เปิดใช้งานไอคอนคอลเลกชัน",
        r2: "การตั้งค่า Wishlist บนหน้าคอลเลกชัน",
        r3: "คุณต้องเปิดใช้งานวิดเจ็ตนี้ก่อนเพื่อให้สามารถใช้ฟังก์ชัน Wishlist ได้จากหน้าคอลเลกชันและหน้าอื่น ๆ",
        r4: "คุณได้เปิดใช้งานไอคอนคอลเลกชันแล้ว โปรดไปยังขั้นตอนถัดไป",
        r5: "ขั้นตอนที่ 2 เสร็จสมบูรณ์แล้ว โปรดไปยังขั้นตอนถัดไป",
        r6: "ก่อนหน้า",
        r7: "บันทึกและถัดไป",
        r8: "ขั้นตอนที่ 2 - เลือกภาษาสำหรับแอปของคุณ",
        r9: "บันทึกและเสร็จสิ้น",

        q1: "ขั้นตอนที่ 3 - เลือกภาษาสำหรับแอปของคุณ",
        q2: "หากคุณพบปัญหาเกี่ยวกับความเข้ากันได้ของธีมหรือจำเป็นต้องปรับแต่งแอป Wishlist Guru ของเรา โปรดติดต่อเราได้ที่",

        y1: "ภาษาสำหรับผู้ดูแลระบบ",
        y2: "เลือกภาษาสำหรับฝั่งผู้ดูแลระบบของคุณ",
        y3: "ภาษาหน้าร้าน",
        y4: "เลือกภาษาสำหรับข้อความตัวอักษรของคุณ",

    },
    uk: {
        sG: "Посібник із налаштування Wishlist Guru",
        sGSH: "Будь ласка, виконайте наведені нижче кроки, щоб почати використовувати застосунок",
        s1: "КРОК 1 з 3: Виберіть тему та активуйте застосунок",
        ct: "Виберіть тему",
        active: "Активний",
        inActive: "Деактивовано",
        n2: "Тут ви можете вибрати, де ви хочете активувати та протестувати застосунок Wishlist Guru. Будь ласка, переконайтеся, що Вмикання Wishlist Guru App Embed увімкнено через Редактор тем.",
        n3: "Увімкнути",
        n4: "Відкриється нова вкладка, де ви зможете увімкнути блок вбудовування теми, пов'язаний з нашим застосунком. Дотримуйтесь наведеного знімка екрана, а потім поверніться сюди й перейдіть до наступного кроку.",
        n5: "Примітка:",
        n6: "КРОК 1 - Виберіть тему та активуйте застосунок",
        n7: "Застосунок наразі працює на",
        n8: "Змінити тему",
        n9: "Крок 1 завершено, перейдіть до наступного кроку",

        r1: "КРОК 2 - Увімкніть іконку колекції",
        r2: "Налаштування списку бажань на сторінці колекції",
        r3: "Вам потрібно спочатку увімкнути цей віджет, щоб функція списку бажань могла використовуватися на сторінках колекцій та інших сторінках.",
        r4: "Ви вже увімкнули іконку колекції, перейдіть до наступного кроку",
        r5: "Крок 2 завершено, перейдіть до наступного кроку",
        r6: "Попередній",
        r7: "Зберегти та далі",
        r8: "КРОК 2 - Виберіть мову для вашого застосунку",
        r9: "Зберегти та завершити",

        q1: "КРОК 3 - Виберіть мову для вашого застосунку",
        q2: "Якщо у вас виникнуть проблеми з сумісністю теми або вам потрібна будь-яка кастомізація для нашого застосунку Wishlist Guru, не соромтеся зв'язатися з нами за адресою",

        y1: "Мова сторони адміністратора",
        y2: "Виберіть мову для сторони адміністратора",
        y3: "Мова вітрини магазину",
        y4: "Виберіть мову для ваших текстових повідомлень",

    },
    vi: {
        sG: "Hướng Dẫn Cài Đặt Wishlist Guru",
        sGSH: "Vui lòng hoàn tất các bước dưới đây để bắt đầu sử dụng ứng dụng",
        s1: "BƯỚC 1 trong 3: Chọn giao diện và kích hoạt ứng dụng",
        ct: "Chọn giao diện",
        active: "Kích hoạt",
        inActive: "Đã tắt",
        n2: "Tại đây bạn có thể chọn nơi muốn kích hoạt và thử nghiệm ứng dụng Wishlist Guru. Vui lòng đảm bảo rằng Đã bật Wishlist Guru App Embed thông qua Trình chỉnh sửa giao diện.",
        n3: "Bật",
        n4: "Một tab mới sẽ mở ra nơi bạn có thể bật khối nhúng giao diện liên quan đến ứng dụng của chúng tôi. Hãy làm theo ảnh chụp màn hình được cung cấp, sau đó quay lại đây và tiếp tục bước tiếp theo.",
        n5: "Lưu ý:",
        n6: "BƯỚC 1 - Chọn giao diện và kích hoạt ứng dụng",
        n7: "Ứng dụng hiện đang hoạt động trên",
        n8: "Chuyển giao diện",
        n9: "Bước 1 đã hoàn tất, vui lòng tiếp tục bước tiếp theo",

        r1: "BƯỚC 2 - Bật biểu tượng bộ sưu tập",
        r2: "Cài đặt Wishlist trên trang bộ sưu tập",
        r3: "Bạn cần bật tiện ích này trước để có thể sử dụng chức năng Wishlist từ các trang bộ sưu tập và các trang khác.",
        r4: "Bạn đã bật biểu tượng bộ sưu tập, vui lòng tiếp tục bước tiếp theo",
        r5: "Bước 2 đã hoàn tất, vui lòng tiếp tục bước tiếp theo",
        r6: "Trước",
        r7: "Lưu và Tiếp",
        r8: "BƯỚC 2 - Chọn ngôn ngữ cho ứng dụng của bạn",
        r9: "Lưu và Hoàn tất",

        q1: "BƯỚC 3 - Chọn ngôn ngữ cho ứng dụng của bạn",
        q2: "Nếu bạn gặp bất kỳ sự cố nào về khả năng tương thích giao diện hoặc cần bất kỳ tùy chỉnh nào cho ứng dụng Wishlist Guru của chúng tôi, vui lòng liên hệ với chúng tôi tại",

        y1: "Ngôn ngữ phía quản trị viên",
        y2: "Chọn ngôn ngữ cho phía quản trị viên của bạn",
        y3: "Ngôn ngữ cửa hàng",
        y4: "Chọn ngôn ngữ cho tin nhắn văn bản của bạn",

    }
}